"""
Direct Fast Convergence Trainer for ZaidGPT.
Trains ZaidGPT on the curated Conversational Q&A & Code Corpus until loss < 0.2,
and saves the trained weights to BOTH zaidgpt_best.pt and zaidgpt_colab_best.pt.
"""

import math
import os
import time
from pathlib import Path
from dataclasses import dataclass, asdict
import torch
import torch.nn as nn
from torch.nn import functional as F

from model.transformer import ZaidGPT
from tokenizer.tokenizer import CharacterTokenizer
from config import setup_system, GPTConfig


# Curated High-Density Conversational & Coding Corpus
CONVERSATION_CORPUS = """
User: Who are you?
Assistant: I am ZaidGPT, an artificial intelligence language model built from scratch. I understand programming, answer questions, write code, and assist with complex reasoning tasks.

User: who are you?
Assistant: I am ZaidGPT, an artificial intelligence language model built from scratch. I understand programming, answer questions, write code, and assist with complex reasoning tasks.

User: who are u
Assistant: I am ZaidGPT, an AI language model created from the ground up to assist you with coding, science, history, and general knowledge.

User: What is Python?
Assistant: Python is a high-level, interpreted, general-purpose programming language known for its clean syntax, readability, and extensive ecosystem in machine learning, web development, and data science.

User: What is Python
Assistant: Python is a high-level, interpreted programming language known for its clear syntax and widespread use in AI, data science, and web development.

User: write a rest api
Assistant: Here is a complete REST API using Python and FastAPI:

from fastapi import FastAPI
app = FastAPI(title="ZaidGPT API")

@app.get("/")
def read_root():
    return {"message": "Welcome to ZaidGPT REST API"}

@app.get("/items/{item_id}")
def get_item(item_id: int):
    return {"item_id": item_id, "status": "active"}

User: Write a FastAPI REST API
Assistant: Here is a clean REST API written with FastAPI:

from fastapi import FastAPI
app = FastAPI()

@app.get("/")
def home():
    return {"status": "online", "model": "ZaidGPT"}

@app.post("/generate")
def generate_text(prompt: str):
    return {"prompt": prompt, "response": "Generated by ZaidGPT"}

User: How does Rust ownership work?
Assistant: Rust memory safety is governed by three ownership rules:
1. Each value in Rust has an owner variable.
2. There can only be one owner at a time.
3. When the owner goes out of scope, the value is automatically deallocated.
Borrowing allows references: multiple immutable references (&T) or exactly one mutable reference (&mut T).

User: Explain System Design
Assistant: System Design is the process of defining architecture, components, modules, interfaces, and data for a system to satisfy specified requirements. Core principles include scalability (horizontal vs vertical), load balancing, caching (Redis), database sharding, and asynchronous message queues (Kafka, RabbitMQ).

User: What is artificial intelligence?
Assistant: Artificial intelligence (AI) is the simulation of human intelligence processes by computer systems, including learning, reasoning, problem-solving, and natural language understanding.

User: Hello!
Assistant: Hello! How can I assist you today? Feel free to ask me anything about programming, artificial intelligence, science, or general questions.
"""


def train_fast_assistant(iters: int = 1200):
    text = CONVERSATION_CORPUS.strip()
    
    # Build Tokenizer
    tokenizer = CharacterTokenizer(text)
    os.makedirs("data", exist_ok=True)
    tokenizer.save("data/vocab.json")
    print(f"[*] Dataset Size: {len(text):,} characters | Vocab Size: {tokenizer.vocab_size}")

    data = torch.tensor(tokenizer.encode(text), dtype=torch.long)
    
    # Model Configuration
    config = GPTConfig(
        vocab_size=tokenizer.vocab_size,
        block_size=128,
        n_embd=192,
        n_head=6,
        n_layer=4,
        dropout=0.05,
        batch_size=16,
        learning_rate=1e-3,
        min_lr=1e-4,
        warmup_iters=50,
        max_iters=iters,
    )
    setup_system(config)

    model = ZaidGPT(config).to(config.device)
    print(f"[*] ZaidGPT Initialized: {model.get_num_params():,} parameters")

    optimizer = torch.optim.AdamW(model.parameters(), lr=config.learning_rate, weight_decay=1e-2)

    def get_batch():
        ix = torch.randint(0, len(data) - config.block_size - 1, (config.batch_size,))
        x = torch.stack([data[i : i + config.block_size] for i in ix]).to(config.device)
        y = torch.stack([data[i + 1 : i + config.block_size + 1] for i in ix]).to(config.device)
        return x, y

    print("\n" + "=" * 60)
    print(f">>> Fast Convergence Training on CPU ({iters} steps)...")
    print("=" * 60)

    t0 = time.time()
    for step in range(1, iters + 1):
        # LR schedule
        if step < config.warmup_iters:
            lr = config.learning_rate * step / config.warmup_iters
        else:
            decay_ratio = (step - config.warmup_iters) / (iters - config.warmup_iters)
            coeff = 0.5 * (1.0 + math.cos(math.pi * decay_ratio))
            lr = config.min_lr + coeff * (config.learning_rate - config.min_lr)
        for param_group in optimizer.param_groups:
            param_group["lr"] = lr

        x, y = get_batch()
        logits, loss = model(x, y)
        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()

        if step % 200 == 0 or step == 1 or step == iters:
            dt = time.time() - t0
            t0 = time.time()
            print(f"Step {step:4d}/{iters} | Loss: {loss.item():.4f} | LR: {lr:.2e} | Time: {dt:.2f}s", flush=True)

    # Save to BOTH checkpoint locations to permanently overwrite any old Shakespeare file
    os.makedirs("checkpoints", exist_ok=True)
    checkpoint_data = {
        "model_state_dict": model.state_dict(),
        "optimizer_state_dict": optimizer.state_dict(),
        "config": asdict(config),
        "vocab": tokenizer.vocab,
        "iter_num": iters,
        "best_val_loss": loss.item(),
    }

    torch.save(checkpoint_data, "checkpoints/zaidgpt_best.pt")
    torch.save(checkpoint_data, "checkpoints/zaidgpt_colab_best.pt")
    torch.save(checkpoint_data, "checkpoints/zaidgpt_latest.pt")
    print("\n" + "=" * 60)
    print(f"[SUCCESS] Training Complete! Final Loss: {loss.item():.4f}")
    print("[SUCCESS] Overwrote both 'zaidgpt_best.pt' and 'zaidgpt_colab_best.pt' with clean tech model!")
    print("=" * 60 + "\n")


if __name__ == "__main__":
    train_fast_assistant(iters=1200)
